name: Deploy to EC2

on:
  push:
    branches:
      - github_actions

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo docker stop laravelOnlogn
            sudo docker rm laravelOnlogn
            sudo docker pull issiwara/laravel_nlogn
            sudo docker run -d -p 80:3000 --name laravelOnlogn issiwara/laravel_nlogn
